AMP_JSON_API_CLIENT_ID = "api_client_id"
AMP_JSON_API_KEY = "api_key"
AMP_JSON_HASH = "hash"
AMP_JSON_IP = "ip"
AMP_JSON_URL = "url"
AMP_JSON_CONNECTOR_GUID = "connector_guid"
AMP_JSON_QUERY = "query"
AMP_ENDPOINT_NOT_FOUND = "Specified endpoint not found"
